/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.63).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Goal;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2024-10-24T19:33:46.963266381Z[GMT]")
@Validated
public interface GoalsApi {

    @Operation(summary = "Create a new goal", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Goal created", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Goal.class))) })
    @RequestMapping(value = "/goals",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Goal> createGoal(@Parameter(in = ParameterIn.DEFAULT, description = "Goal object that needs to be created", required=true, schema=@Schema()) @Valid @RequestBody Goal body
);


    @Operation(summary = "Delete a goal by ID", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "204", description = "Goal deleted"),
        
        @ApiResponse(responseCode = "404", description = "Goal not found") })
    @RequestMapping(value = "/goals/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteGoal(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("id") String id
);


    @Operation(summary = "Get all goals", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "A list of goals", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Goal.class)))) })
    @RequestMapping(value = "/goals",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Goal>> getAllGoals();


    @Operation(summary = "Get a goal by ID", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "A single goal", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Goal.class))),
        
        @ApiResponse(responseCode = "404", description = "Goal not found") })
    @RequestMapping(value = "/goals/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Goal> getGoalById(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("id") String id
);


    @Operation(summary = "Update a goal by ID", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Goal updated", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Goal.class))),
        
        @ApiResponse(responseCode = "404", description = "Goal not found") })
    @RequestMapping(value = "/goals/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Goal> updateGoal(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("id") String id
, @Parameter(in = ParameterIn.DEFAULT, description = "Goal object that needs to be updated", required=true, schema=@Schema()) @Valid @RequestBody Goal body
);

}

